### ISSUE TITLE
TypeError while testing dynamism

### ISSUE THREAD

**Issue by GoogleCodeExporter** [flan/staticdhcpd#42]
```
What steps will reproduce the problem?
1. Configured dynamism in conf.py
2. Started staticDHCPd in non-daemon mode
3. waited for next dhcp request

What is the expected output? What do you see instead?

TypeError: __init__() got an unexpected keyword argument 'gateway'

What version of the product are you using? On what operating system?

2.0.0 rc1

Please provide any additional information below.

Full console output: 

2015-05-02 11:09:32,226 : WARNING : ----------------------------------------
2015-05-02 11:09:32,228 : WARNING : All subsystems initialised; now serving
2015-05-02 11:09:32,229 : WARNING : ----------------------------------------
2015-05-02 11:09:34,058 : INFO : REQUEST:INIT-REBOOT from 78:fd:94:c6:17:92 for 
172.29.1.51
2015-05-02 11:09:34,059 : INFO : Dynamic REQUEST:INIT-REBOOT from 
78:fd:94:c6:17:92 for 172.29.1.51 in pool 'legacy-0'
2015-05-02 11:09:34,063 : INFO : Bound 172.29.1.231 to 78:fd:94:c6:17:92 in 
pool 'legacy-0' until Tue May  5 11:09:34 2015
2015-05-02 11:09:34,066 : CRITICAL : Unable to handle REQUEST:INIT-REBOOT from  
78:fd:94:c6:17:92:
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/staticdhcpdlib/dhcp.py", line 391, in wrappedHandler
    f(self, wrapper)

  File "/usr/local/lib/python2.7/dist-packages/staticdhcpdlib/dhcp.py", line 577, in _handleDHCPRequest
    self._handleDHCPRequest_INIT_REBOOT(wrapper)

  File "/usr/local/lib/python2.7/dist-packages/staticdhcpdlib/dhcp.py", line 629, in _handleDHCPRequest_INIT_REBOOT
    definition = wrapper.retrieveDefinition()

  File "/usr/local/lib/python2.7/dist-packages/staticdhcpdlib/dhcp.py", line 375, in retrieveDefinition
    self.pxe and self._pxe_options or None

  File "/etc/staticDHCPd/_handlers.py", line 12, in handleUnknownMAC
    return _dynamic_pool.handle(method, packet, mac, client_ip)

  File "/etc/staticDHCPd/dynamism.py", line 279, in handle
    definition = self._allocate(mac, client_ip)

  File "/etc/staticDHCPd/dynamism.py", line 121, in wrapped_method
    extra=None

TypeError: __init__() got an unexpected keyword argument 'gateway'

```

Original issue reported on code.google.com by `bhms.rob...@gmail.com` on 2 May 2015 at 6:30

**Comment by flan** [comment]
Sorry, this got forgotten in the codebase migration

I think you were using an old version of the dynamism script -- newer versions have the definition of **init** between lines 126 and 131 and includes a keyword argument for gateway.
