### ISSUE TITLE
dev null dup2 Bad file descriptor

### ISSUE THREAD

**Issue by alexxroche** [flan/staticdhcpd#88]
I have a working staticDHCPd for diagnostics. (Thank you! This is so helpful at times.)
If I change the /etc/staticDHCPd/conf.py to
```ini
DEBUG = True
DAEMON = True
```
#### and then:
root@linux:/etc/staticDHCPd# staticDHCPd
```python3
Traceback (most recent call last):
  File "/usr/local/bin/staticDHCPd", line 97, in <module>
    _daemonise()
  File "/usr/local/bin/staticDHCPd", line 88, in _daemonise
    os.dup2(open('/dev/null', 'r').fileno(), sys.stdin.fileno())
OSError: [Errno 9] Bad file descriptor
```

**Comment by alexxroche** [comment]
I downloaded the latest release and patched staticDHCPd with
```pthon2
    dev_null_r = open('/dev/null', 'r')
    dev_null_a = open('/dev/null', 'a+')
    dev_null_0 = open('/dev/null', 'a+', 0)
    os.dup2(dev_null_r.fileno(), sys.stdin.fileno())
    os.dup2(dev_null_a.fileno(), sys.stdout.fileno())
    os.dup2(dev_null_0.fileno(), sys.stderr.fileno())
    -os.dup2(open('/dev/null', 'r').fileno(), sys.stdin.fileno())
    -os.dup2(open('/dev/null', 'a+').fileno(), sys.stdout.fileno())
    -os.dup2(open('/dev/null', 'a+', 0).fileno(), sys.stderr.fileno())
```

But version 2 seems to have already patched this with
```python2
    devnull = os.open('/dev/null', os.O_RDWR)
    os.dup2(devnull, sys.stdin.fileno())
    os.dup2(devnull, sys.stdout.fileno())
    os.dup2(devnull, sys.stderr.fileno())
```
So this issue would be fixed by having a new release candidate? (Its been 7 years since the last release, so maybe its time?)
